### ISSUE TITLE
TypeError: cannot read property array of undefined in fromGeometry of a custom geometry

### ISSUE THREAD

**Issue by steveliles** [manthrax/THREE-CSGMesh#11]
I have a simple custom geometry created by setting an array of vertices to a BufferGeometry like this:

```
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.BufferAttribute(vertices, 3));
  geometry.computeVertexNormals();
```

This renders just fine, but when I try to create a BSP from the mesh I get a TypeError as below, and I don't know where to go from here to get it working. Any clues much appreciated!

demo: https://codesandbox.io/s/manthrax-crash-jm533?file=/src/App.js:2576-2732

```
TypeError
Cannot read property 'array' of undefined

Function._csgLib.CSG.fromGeometry
/src/three-csg.js:60:25
  57 | const nx = normalattr.array[vp];
  58 | const ny = normalattr.array[vp + 1];
  59 | const nz = normalattr.array[vp + 2];
> 60 | const u = uvattr.array[vt];
     |                 ^
  61 | const v = uvattr.array[vt + 1];
  62 | vertices[j] = new Vertex(
  63 |   {

View compiled
Function._csgLib.CSG.fromMesh
/src/three-csg.js:94:18
  91 | const ttvv0 = new THREE.Vector3();
  92 | const tmpm3 = new THREE.Matrix3();
  93 | CSG.fromMesh = function (mesh, objectIndex) {
> 94 |   const csg = CSG.fromGeometry(mesh.geometry, objectIndex);
     |                  ^
  95 |   tmpm3.getNormalMatrix(mesh.matrix);
  96 |   for (let i = 0; i < csg.polygons.length; i++) {
  97 |     const p = csg.polygons[i];
```

**Comment by manthrax** [comment]
Hey @steveliles .. sorry I didn't see this till now.. did you figure out a workaround?

I've added a check for missing uvs.. but I haven't verified that threejs itself wont barf on missing UVs.. worst case, you may have to geometry.addAttribute(new THREE.BufferAttribute('uv', with an empty array...

let me know if this build helps..
