### ISSUE TITLE
How check if 2 Objects have a intersection result

### ISSUE THREAD

**Issue by MichaelHilgers** [manthrax/THREE-CSGMesh#15]
Hi

how i can check/test if 2 objects intersect?

Thanks

**Comment by manthrax** [comment]
Good question. I suppose you could attempt the intersction operation and check whether the resulting geometry is empty? perhaps via resultingMesh.geometry.attributes.points.array.length==0 ?

**Comment by MichaelHilgers** [comment]
Hi

and how i can check if MeshB geometry is complity in MeshA geometry?

**Comment by manthrax** [comment]
Perhaps you could subtract MeshA from MeshB and check for an empty result as described above?

**Comment by MichaelHilgers** [comment]
> Good question. I suppose you could attempt the intersction operation and check whether the resulting geometry is empty? perhaps via resultingMesh.geometry.attributes.points.array.length==0 ?

hm.. it's not working an Three.js v0.133.1
How can i check if result geometry is a valid geometry ?

Thanks

**Comment by manthrax** [comment]
Depends what you mean by valid. You could check that it has geometry.attributes.points.array.length > 0 and geometry.index.array.length >= 3 ?
