### ISSUE TITLE
Do multiple substract on 1 Mesh

### ISSUE THREAD

**Issue by MichaelHilgers** [manthrax/THREE-CSGMesh#17]
Hello

Can i do multiple substracts on 1 Mesh?
When i substract multiple Meshs from one Mesh i received corrupted Meshs?
How can i substract multipletime one Mesh?

In my sample the resulting mesh is devided in two, after than i do a second substract, the resulting mesh is corrupt.

Thanks

**Comment by manthrax** [comment]
Can you provide a reproduction?

Here is a glitch you can use as a template to frame your problem... Just replace the logic in RingSlicer.js

https://csg-ring-embossing.glitch.me
