### ISSUE TITLE
Stuck on Any Operation between two STL files

### ISSUE THREAD

**Issue by Tajammal-Maqbool** [manthrax/THREE-CSGMesh#19]
When I use one STL file and one any three js geometry then all operations are performed but when I use both STL files then not any error comes but web page going to stuck not perform any action. issue is when two STL files used and any operation is performed it goes stuck not perform further any work it looks like as it goes an unlimited loop that not beaks and not return from. You have any solution. Please tell me urgently.

**Comment by manthrax** [comment]
How many triangles are in each STL? The time it takes to perform operations is quadtratic with respect to the number of triangles in A and B.. so   1 triangle -> 100 triangles is faster than 10 triangles to 10 triangles.. and 100 triangles to 100 triangles will be VERY slow.

Sometimes you can break the operation into multiple operations.. by taking object A.. then reducing it by colliding with a smaller box around the area that you know will be collided.. then taking the result and doing the operation with B, and then merging them back together. I show this type of operation in one of the examples in the repo, embossing some text onto a complex STL type object.

It's possible there is still a bug that you have found, but without more information or a test reproduction, It will be hard to identify.
