### ISSUE TITLE
Meshes are re-positioned back at the origin before subtraction,union,etc. operations

### ISSUE THREAD

**Issue by ninhja** [manthrax/THREE-CSGMesh#2]
Hello there! I have been trying to subtract shapes using CSG.js and Three.js, and haven't had any luck with ThreeCSG.js, so I am trying to use your library instead. Subtracting the shapes is working fine, but I am having one issue with your library that I cannot get around. 

I am using your helper function doCSG( ) to convert Three.Mesh cubes into CSG objects, then subtract one cube from the other. Specifically, I want to subtract a smaller cube from the larger cube so that the end result looks like a cube with a small chunk taken out of one corner. 

I'm using your helper function, doCSG( ). And here's the basic code for subtracting the cubes: 

```
var meshA = new THREE.Mesh(new THREE.BoxGeometry(10,10,10), material);
	var meshB = new THREE.Mesh(new THREE.BoxGeometry(9,9,9));
	meshB.position.add(new THREE.Vector3( 10,10,10));
	meshA.position.add(new THREE.Vector3( 5, 5, 5));
	var meshC = doCSG( meshA,meshB, 'subtract',meshA.material);
	scene.add(meshC);
```

However, in the rendered scene, when I end up with is simply the larger cube. After doing some experimentation, I realize that the smaller cube was indeed subtracted from the larger cube, but both cubes were repositioned at the origin before the subtraction operation. 

I would very much appreciate it if you could fix this issue, so that the positions of meshes are preserved before performing subtraction operations or any other operation. I suspect the issue has something to do with with the matrix transformations in the fromMesh() function but I am not sure. Thank you very much!

**Comment by manthrax** [comment]
I don't see anywhere in the code where the input mesh matrices are being mutated.. could you perhaps supply a test case showing your problem? Sorry for the delay in responding, I just saw the issue.
Thanks for checking on it :)

**Comment by kuzznicki** [comment]
@ninhja try updating meshA and meshB matrices before CSG operations
```
var meshA = new THREE.Mesh(new THREE.BoxGeometry(10,10,10), material);
var meshB = new THREE.Mesh(new THREE.BoxGeometry(9,9,9));
meshB.position.add(new THREE.Vector3( 10,10,10));
meshA.position.add(new THREE.Vector3( 5, 5, 5));
meshA.updateMatrix();
meshB.updateMatrix();
var meshC = doCSG( meshA,meshB, 'subtract',meshA.material);
scene.add(meshC);
```
