### ISSUE TITLE
conversion back to THREE.Mesh misses the uv

### ISSUE THREAD

**Issue by PulgaFeroz** [manthrax/THREE-CSGMesh#3]
In the loop at line 453:

       for(var j=3;j<=pvlen;j++){

It does the calculation for UV, but most of what's done is lost and not utilized in the created mesh (fvuv, fuv and fnml)

Note that there are a few other things, while trying to convert it to typescript the compiler found other issues, for example:

Line 480:

      m.matrix.decompose(m.position,m.rotation,m.scale)

m.rotation is Euler (latest THREE version as of 26/6) but matrix.decompose expects a quaternion, im not sure if this would fix it:

      m.matrix.decompose(m.position, new THREE.Quaternion().setFromEuler(m.rotation), m.scale);

then CSG:fromGeometry builds vertices passing a Vector2 as uv, I'm unsure if this works as expected, it then makes a new Vector receiving a Vector2 as constructor parameter (didn't go too deep into it, not sure if there's actually an issue)

Any plans to convert / adapt it to typescript? 

Anyway sorry for the 'many issues one report' :D

**Comment by PulgaFeroz** [comment]
Oh, bloody linter, the UV calculation was used indeed

**Comment by manthrax** [comment]
Thanks for following up on it :) Definitely looks like you found some issues. If you want to make a PR I can fix them.
I have no immediate plans to convert to TS, but I would integrate bindings if someone provided them, providing the vanilla path remains viable. If its too much hassle, feel free to fork :) and maybe add an issue in this repo linking to your fork for anyone looking for fixes/ts/etc.

**Comment by xawill** [comment]
[Here](https://github.com/Jiro-Digital/three-csg-ts) is a TS rewrite of this library. And your issue looks very much like [this one](https://github.com/Jiro-Digital/three-csg-ts/issues/2) in the aforementioned repository (which has been resolved in v1.0.5). So if this is really the same issue, I guess either you can copy the fix in your PR for this repo or you can migrate to the TS rewrite.

**Comment by manthrax** [comment]
Sorry for the delay, and thanks again @PulgaFeroz .. I've pushed your fix. :)

**Comment by manthrax** [comment]
I've also added support for vertex colors, and material ids/groups.. and primitive webworker support. The core algorithm is also decoupled now, so it could be adapted for frameworks other than three.
