### ISSUE TITLE
Multi Material

### ISSUE THREAD

**Issue by JonDevoS** [manthrax/THREE-CSGMesh#4]
HI, i have problem with converted mesh materials
on right side original mesh
on bottom subtracted mesh
and on middle CSG mesh
here is a screen shot and a simple part of code
`       let texture1: THREE.Texture = Textures.getTexture('1');
        texture1.wrapS = texture1.wrapT = THREE.RepeatWrapping;
        texture1.repeat.set(1, 1);
        let texture2: THREE.Texture = Textures.getTexture('2');
        texture2.wrapS = texture2.wrapT = THREE.RepeatWrapping;
        // texture2.repeat.set(1, 0.2);
        let mat1: THREE.MeshBasicMaterial = new THREE.MeshBasicMaterial({map: texture1});
        let mat2: THREE.MeshBasicMaterial = new THREE.MeshBasicMaterial({map: texture2});
        let materials: Array<THREE.MeshBasicMaterial> = [
            mat1,
            mat2,
            mat2
        ];
        let meshA: THREE.Mesh = this.tjs.addMesh(new THREE.Mesh(new THREE.CylinderGeometry(4, 4, 3, 20), materials));
        let meshB: THREE.Mesh = this.tjs.addMesh(new THREE.Mesh(new THREE.CylinderGeometry(2, 2, 3, 20), materials));
        // Create a bsp tree from each of the meshes
        let bspA: CSG = CSG.fromMesh(meshA);
        let bspB: CSG = CSG.fromMesh(meshB);

        // Subtract one bsp from the other via .subtract. other supported modes are .union and .intersect
        let bspResult: CSG = bspA.subtract(bspB);

        // Get the resulting mesh from the result bsp
        this.tjs.addMesh(CSG.toMesh(bspResult, meshA.matrix)).material = materials;

        meshA.position.x = 9;
        meshB.position.z = 9;`

or maybe you know how to figure out with this issue
sorry for my Eanglish :)
Thanks!
![qq](https://user-images.githubusercontent.com/19163266/94700152-d79cc600-0343-11eb-9856-e7db30efec51.png)

**Comment by manthrax** [comment]
Hard to tell what's going on there. Can you show wireframes of all the pieces?
