### ISSUE TITLE
subtract() and intersect() are swapped in some operations

### ISSUE THREAD

**Issue by agviegas** [manthrax/THREE-CSGMesh#6]
Hola! 🙂

I have noticed that in some operations the `subtract()` and `intersect()` are swapped. This means that even though I am using operand1.subtract(operand2), the result is the intersection of both geometries. If I do operand1.intersect(operand2), the result is the difference. 

I am using this for the [Three.js IFC Loader](https://github.com/agviegas/IFC.js). The vast majority of the boolean operations are simple parallelepiped (subtracting the opening of a window or a door). For example (wall and windows/doors are separated; the openings need to be applied only on the walls): 

![image](https://user-images.githubusercontent.com/56475338/104773425-555ed300-5775-11eb-9377-d92929ac5d5c.png)

If I make the volumes I am using for the operations visible:

![image](https://user-images.githubusercontent.com/56475338/104773495-6f98b100-5775-11eb-90d4-3695f4465506.png)

As said, it works fine in the majority of the cases. But I have come across a door with an opening that is a bit more complex, but still quite simple (a sliding door): 

![image](https://user-images.githubusercontent.com/56475338/104773642-ab337b00-5775-11eb-9faf-298eed975112.png)

What you see in the image is the volume that needs to be subtracted overlapped with the result; so, it has made an intersect operation. If I change `subtract()` by `intersect()`, the result is a subtraction (what I want):

![image](https://user-images.githubusercontent.com/56475338/104773853-fbaad880-5775-11eb-9cbe-47454967a23f.png)
![image](https://user-images.githubusercontent.com/56475338/104774010-36147580-5776-11eb-9d51-7fd22bbe5deb.png)

Do you know what might be causing this? Thank you in advance!

**Comment by manthrax** [comment]
I'm guessing this is related to the same epsilon issue you brought up in another report. I'm closing this for now, but if it's still blocking you after playing with Plane.EPSILON, go ahead and file again, or contact me manthrax@gmail.com
