### ISSUE TITLE
Remaining face after subtract operation

### ISSUE THREAD

**Issue by agviegas** [manthrax/THREE-CSGMesh#7]
Hi again!

After some subtraction operations, there is a remaining face in the result. 

In this case, I am given a wall and a sloped roof as separate objects. The wall is given as a parallelepiped and I am using subtract operations to clip it with the shape of the roof.

![image](https://user-images.githubusercontent.com/56475338/104828662-1d868700-586c-11eb-8451-52fb09c0b883.png)

Nevertheless, when I apply the operation, this is the result:

![image](https://user-images.githubusercontent.com/56475338/104828721-a271a080-586c-11eb-8eb1-a2da161e9581.png)
![image](https://user-images.githubusercontent.com/56475338/104828737-bcab7e80-586c-11eb-9f5a-ee56862764fc.png)

As you can see, the operation has been carried out correctly, but there is a face that remains. I am not sure wether this is a precission problem or something else. 

I am aware that knowing the cause of this issue might be hard, but I was hoping to find a way around this problem (maybe a way to tweak the precission of the CSG operation or a way to detect when this kind of isolated face is generated to filter it out).

Thank you very much in advance! 🙂

**Comment by manthrax** [comment]
You can change the "EPSILON" in the Plane class .. search for Plane.EPSILON
In csgmesh.js Perhaps try making it smaller for your case, or experiment. The epsilon is used to determine how closely points have to align to be considered part of the same plane.
