### ISSUE TITLE
The issue doesn't work to make a hole in a plane

### ISSUE THREAD

**Issue by belopot** [manthrax/THREE-CSGMesh#8]
Hi

Thank you for your CSGMesh. I have one problem in CSG-the "subtract" operation. One I tried to make a hole in the plane, I got the problem. The problem is that after the operation, part of the cube is attached to the plane. Please take a look at the screenshots

![image](https://user-images.githubusercontent.com/46432435/112755364-56e71b80-8fae-11eb-9f88-a9c919cde911.png)

![image](https://user-images.githubusercontent.com/46432435/112755382-6f573600-8fae-11eb-95da-baf4d23dd983.png)

I want to get the result like the image below(I used the Boolean object in 3dsMax)
![image](https://user-images.githubusercontent.com/46432435/112755507-f60c1300-8fae-11eb-9c11-8ba148fe8636.png)

Can you resolve the issue?

Thank you

**Comment by manthrax** [comment]
A plane is a single sided primitive so it doesn't have volume. SO to the CSG library it's the same as a box that extends to infinity. To get a cutout like that to work, you'll probably need to use a flattened cube as the red primitive... Once the operation is finished.. it's pretty easy to loop through the triangles and discard any that have vertices where .z > 0 or whatever to get you back to a 2d cutout plane.
